apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    build: services-api
  name: services-api
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: services-api:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://git.zby.icdc.io/icdc/admin/services-api.git
    sourceSecret:
      name: os-deploy-idc
    type: Git
  strategy:
    dockerStrategy:
      env:
      - name: RAILS_ENV
        value: development
      - name: BUILD_BRANCH
        value: dev
      - name: GIT_AUTH
        valueFrom:
          secretKeyRef:
            key: GIT_CRED
            name: git-cred
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - gitlab:
        secretReference:
          name: services-api-push-event
      type: GitLab
