openapi: 3.0.0
info:
  version: '1.0'
  title: 'Delivery API'
  # description: 'Provides VPN service for account infrastructure'
# servers:
#   # Added by API Auto Mocking Plugin
#   - description: SwaggerHub API Auto Mocking
#     url: https://virtserver.swaggerhub.com/ahrechushkin/vpn/1.0
tags:
  # - name: Releases
  #   description: Releases management
  - name: Services
    description: Services management
  # - name: Statuses
  #   description: Statuses management
  # - name: Subscriptions
  #   description: Subscriptions management
  # - name: Updates
  #   description: Updates management
  # - name: Versions
  #   description: Verions management
     
paths:    
  /services/{service_name}/downgrade:
    parameters:
      - in: path
        name: service_name
        schema:
          type: string
        required: true
    get:
      tags:
        - 'Services'
      summary: Get downgrade versions for services
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: array
                    example: 
                      - "2.0.2"
                      - "2.0.1"
    put:
      tags:
       - 'Services'
      summary: Downgrade vesion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                version:
                  type: string
                  example: 2.0.0
      responses:
        '204':
          description: 'No content'
          
  /services/{service_name}/update:
    parameters:
      - in: path
        name: service_name
        schema:
          type: string
        required: true
    put:
      tags:
       - 'Services'
      summary: Update vesion
      responses:
        '200':
          description: 'Success'
        '204':
          description: 'No content'
    get:
      tags:
       - 'Services'
      summary: Update vesion
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                example:
                  - type: object
                    properties:
                      version: 1.0.2
                      tag: latest
                      release: 1.0
                      date: 2021-09-09
                      required:
                        api-gateway: 1.0.1
                      aplications:
                        - name: httpd
                          tag: 1.0.1
                          description:
                            warnings: "* warning1\r\n* warning2"
                            features: "* feature1\r\n* feature2"
                            security_fixes: "* security1\r\n* security2"
                            bug_fixes: "* bug1\r\n* bug2"
                            depricated: "* depricated1\r\n* depricated2"
                            known_issues: ""
    
  /services/{service_name}/upgrade:
    parameters:
      - in: path
        name: service_name
        schema:
          type: string
        required: true
    put:
      tags:
       - 'Services'
      summary: Upgrade vesion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                version:
                  type: string
                  example: 2.0.1
      responses:
        '200':
          description: 'Success'
        '204':
          description: 'No content'
          
  /services/{service_name}/version:
    parameters:
      - in: path
        name: service_name
        schema:
          type: string
        required: true
    get:
      tags:
       - 'Services'
      summary: Get release version

      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                example:
                  - type: object
                    properties:
                      version: 1.0.2
                      tag: latest
                      release: 1.0
                      date: 2021-09-09
                      required:
                        api-gateway: 1.0.1
                      aplications:
                        - name: httpd
                          tag: 1.0.1
                          description:
                            warnings: "* warning1\r\n* warning2"
                            features: "* feature1\r\n* feature2"
                            security_fixes: "* security1\r\n* security2"
                            bug_fixes: "* bug1\r\n* bug2"
                            depricated: "* depricated1\r\n* depricated2"
                            known_issues: ""
                    
  /services/{service_name}/service_versions:
    parameters:
      - in: path
        name: service_name
        schema:
          type: string
        required: true
    get:
      tags:
       - 'Services'
      summary: Get release version

                            
                            
  /services/{service_name}:
    delete:
      parameters:
      - in: path
        name: service_name
        schema:
          type: string
        required: true
      - in: query
        name: delete_persistent_data
        schema:
          type: string
          example: true
        optional: true
      tags:
        - 'Services'
      summary: Delete service
      responses:
        '204':
          description: 'No content'
  /services/{service_name}/install:
    post:
      parameters:
      - in: path
        name: service_name
        schema:
          type: string
        required: true
        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                version:
                  type: string
                  example: 2.0.1
      tags:
        - 'Services'
      summary: Create service
      
      
      responses:
        '204':
          description: 'No content'
    get:
      parameters:
      - in: path
        name: service_name
        schema:
          type: string
        required: true
      tags:
        - 'Services'
      summary: Create service
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: string
                    example: 1.1.1
          
        
  /service/{service_name}/release:
    get:
      tags:
        - 'Services'
      parameters:
        - in: path
          name: service_name
          schema:
            type: string
          required: true
      summary: Create service
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                example:
                  - type: object
                    properties:
                      version: 1.1.2
                      tag: latest
                      release: 1.0
                      date: 2021-09-09
                      required:
                        api-gateway: 1.0.1
                      aplications:
                        - name: httpd
                          tag: 1.0.1
                          description:
                            warnings: "* warning1\r\n* warning2"
                            features: "* feature1\r\n* feature2"
                            security_fixes: "* security1\r\n* security2"
                            bug_fixes: "* bug1\r\n* bug2"
                            depricated: "* depricated1\r\n* depricated2"
                            known_issues: ""
    
    put:
      tags:
        - 'Services'
      parameters:
        - in: path
          name: service_name
          schema:
            type: string
          required: true
      summary: Create service
      responses:
        '204':
          description: 'No content'
  /status:
    get:
      tags:
        - 'Services'
      summary: Get services statuses
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                example:
                  - common_name: web-server
                    common_status: Complete
                    common_service_installed: true
                    services:
                      web-server-api:
                        service_installed: true
                        service_status: Complete
                      web-server-db:
                        service_installed: true
                        service_status: Complete