---
environment:
  development:
    github_api:
      url: "https://api.github.com"
    github:
      account: "dmemekh"
      repo: "icdc"
      ref: "main"
    os_api:
      url: "https://api.dev.ocp.zby.icdc.io:6443" #<%= ENV['OS_API'] %> !!! Change to mine Halukha_U
      token: "REDACTED" #<%= ENV['OS_TOKEN'] %> !!! Change to mine Halukha_U
  production:
    github_api:
      url: "https://api.github.com"
    github:
      account: "dmemekh"
      repo: "icdc"
      ref: "main"
    os_api:
      url: "https://api.dev.ocp.zby.icdc.io:6443"
      token: "REDACTED"
