---
environment:
  development:
    github_api:
      url: "https://api.github.com"
    github:
      account: <%= ENV['GITHUB_ACCOUNT'] %>
      repo: <%= ENV['GITHUB_REPO'] %>
      ref: <%= ENV['GITHUB_REF'] %>
      # url: <%= ENV['GITHUB_FOLDER'] %> # "https://raw.githubusercontent.com/dmemekh/icdc/main"
    os_api:
      url: <%= ENV['OS_API'] %> #"https://api.dev.ocp.zby.icdc.io:6443"
      token: <%= ENV['OS_TOKEN'] %> #"REDACTED"
  production:
    github_api:
      url: "https://api.github.com"
    github:
      url: <%= ENV['GITHUB_FOLDER'] %> # "https://raw.githubusercontent.com/dmemekh/icdc/main"
    os_api:
      url: <%= ENV['os_api'] %> #"https://api.dev.ocp.zby.icdc.io:6443"
      token: <%= ENV['os_token'] %>
