---
environment:
  test:
    github_api:
      url: "https://api.github.com"
    github:
      account: <%= ENV['GITHUB_ACCOUNT'] %>
      repo: <%= ENV['GITHUB_REPO'] %>
      ref: <%= ENV['GITHUB_REF'] %>
    os_api:
      url: <%= ENV['OS_API'] %> 
      token: <%= ENV['OS_TOKEN'] %>
  development:
    github_api:
      url: "https://api.github.com"
    github:
      account: <%= ENV['GITHUB_ACCOUNT'] %>
      repo: <%= ENV['GITHUB_REPO'] %>
      ref: <%= ENV['GITHUB_REF'] %>
    os_api:
      url: <%= ENV['OS_API'] %> 
      token: <%= ENV['OS_TOKEN'] %>
  production:
    github_api:
      url: "https://api.github.com"
    github:
      account: <%= ENV['GITHUB_ACCOUNT'] %>
      repo: <%= ENV['GITHUB_REPO'] %>
      ref: <%= ENV['GITHUB_REF'] %>
    os_api:
      url: <%= ENV['os_api'] %>
      token: <%= ENV['os_token'] %>